### PR TITLE
Added Video Player Component with Playback Controls, Fullscreen Support, Volume Slider

### PR DESCRIPTION
**Pull request by deep-manral**
Hey coders Myself Deepak Manral  passionate BCA 3rd Year Student and As a Contributor in Girl Script Summer of Code 2024
Added a custom Video Player component to the project with essential playback controls, fullscreen support, volume adjustment slider, and title display.
- Implemented play/pause functionality to control video playback, allowing users to toggle between play and pause states.
- Added support for fullscreen mode, enabling users to expand the video player to fullscreen for an immersive viewing experience.
- Integrated a volume adjustment slider to allow users to control the volume of the video playback according to their preferences.
.

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach screenshot

**Comment by deep-manral** [comment]
###Screenshot of features. Some features are invoked by clicking them like Fullscreen but can be shown  as implemented in screenshot


Screenshot 2024-05-12 165504

**Comment by CDCNaman** [comment]
@deep-manral I have reviewed your PR request. we are developing a video conferencing app like google meet or Zoom not a video streaming platform like YouTube so a Video Player Component is not required.
Thanks for this your contribution  but  Please refer to our initial UI Design https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Curious-Connect?type=design&node-id=0%3A1&mode=design&t=z3lrEU9qYahxcIGX-1

**Comment by CDCNaman** [comment]
and please try to find a Pre-Existing issue and solve it and if you find any difficulty in doing so, Please let us know

**Comment by deep-manral** [comment]
I will further improve or doing well soon sir .You really boost my confidence thanks a lot sir

**Comment by thecuriousteam** [comment]
Thank You @CDCNaman and Always we are with you help and guide @deep-manral **#LetsGrowAllTogether**

**Pull request closed without merging**
