### PR TITLE
#141 Enhance the about us page with more information 

### PR DESCRIPTION
**Pull request by Ayush031**
#141 

I have modified the About Page and divided into 3 sections.
First, created the intro header with typing effect using react-typewriter npm library,
Second, about the curious system
Third, carousel for the given features using react-slick lib, created a json array and mapped the values for optimized usage.

Screenshot for reference:
Screenshot 2024-05-26 213940

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach the screenshot @Ayush031

**Comment by thecuriousteam** [comment]
image

The code is not responsive

**Comment by Ayush031** [comment]
@thecuriousteam I have made pr for #141 issue that is already opened, but you have created a new #241 issue for this. 

image
image

rest footer is same

**Comment by Ayush031** [comment]
@thecuriousteam have made the code responsive

https://www.loom.com/share/d7f5c2b99e5d4504974418983a60aa6c?sid=302b5a57-9f1d-4fae-8263-8b66fa963e38

this is the video of that

**Comment by Ayush031** [comment]
@thecuriousteam I have made the required changes, Let me know if any changes are required

**Pull request merged**
