### PR TITLE
Added Animated icon in Navbar links

### PR DESCRIPTION
**Pull request by SadafKausar2025**
fixed issue no #217 

These Animated icons are giving good look to the projects .

https://github.com/Curious-Ecosystem/Curious-Connect/assets/137484958/113f29e1-06f8-4df9-8db0-f5c1a803e250

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hi @gnnandan 
Can you please review this PR

**Comment by SadafKausar2025** [comment]
Hey @thecuriousteam 
please merge this PR

**Review by SyedImtiyaz-1 — APPROVED** [review]
Great Work, All Set !

**Comment by SadafKausar2025** [comment]
hello @thecuriousteam 
can you please merge this pr?

**Comment by thecuriousteam** [comment]
Hi @SadafKausar2025 

There is some merge conflicts

image

**Comment by SadafKausar2025** [comment]
wait I am correcting it

**Comment by SadafKausar2025** [comment]
hello @thecuriousteam 
now conflicts are resolved please merge it

**Comment by SadafKausar2025** [comment]
hello @gnnandan 
please review this I have resolved the conflict
please merge it

**Comment by SadafKausar2025** [comment]
Hello @thecuriousteam and @gnnandan please merge this pr

**Pull request merged**
