### PR TITLE
feat: added team page

### PR DESCRIPTION
**Pull request by raghavawasthi24**
Added new OurTeam page. 

Screenshot (226)

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please cross check its responsive or not @raghavawasthi24

**Comment by raghavawasthi24** [comment]
> Please cross check its responsive or not @raghavawasthi24

Yes, it is fully responsive.

**Comment by thecuriousteam** [comment]
You have used any map function to fetch data dynamically?

**Comment by raghavawasthi24** [comment]
Yes, I have made a new component named **TeamCard** and mapped it inside **OurTeam**

**Comment by thecuriousteam** [comment]
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Comment by thecuriousteam** [comment]
image

**Comment by thecuriousteam** [comment]
Please find the sample idea

**Comment by thecuriousteam** [comment]
please refer to our directory structure and please the raw data in data.json and from there you can take the data to OurTeam component

**Comment by thecuriousteam** [comment]
please refer to our directory structure and please the raw data in data.json and from there you can take the data to OurTeam component

**Comment by thecuriousteam** [comment]
once it is done 
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Review by thecuriousteam — APPROVED** [review]
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Pull request closed without merging**
