### PR TITLE
[Feature.jsx]-feature cards added/Issue 21 or 12

### PR DESCRIPTION
**Pull request by RishitaChourey**
A responsive feature cards component section added

https://github.com/Curious-Ecosystem/Curious-Connect/assets/128152517/7789de8e-97d2-4c41-8417-8249b81bd5a0

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Its absolutely good design, but please can you add the words, and instead of creating card again and again can you use map function and take the data from as object pass that to mapfunction to render the card

**Comment by thecuriousteam** [comment]
image

**Comment by thecuriousteam** [comment]
Please check this issue to

**Review by thecuriousteam — CHANGES_REQUESTED** [review]
Please check the conversation

**Comment by RishitaChourey** [comment]
Sure ,I will definitely try to make the suggested changes!
Also can you please elaborate about what you mean by "add the words"

**Comment by RishitaChourey** [comment]
@thecuriousteam 
I made the required changes please review it once.

**Comment by thecuriousteam** [comment]
Please attach the screenshot

**Comment by RishitaChourey** [comment]
@thecuriousteam 
https://github.com/Curious-Ecosystem/Curious-Connect/assets/128152517/130ee18b-f275-4dde-b1c6-0d3412c9f6bb

**Review by thecuriousteam — APPROVED** [review]

**Pull request merged**
