### PR TITLE
Responsive UI Enhanced Login Page

### LINKED ISSUE #71: [SignIn.jsx] - design an attractive signin page for curious connect
## **Task Description**
Design an attractive signin page for curious connect

### **Details**
(Please Provide Key Details, if required)
- Please write your code inside the Component/Common directory and call it in Pages of root directory

### **Branch Name**
PR Should be made in `main` Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### **Deadline**
Specify the task deadline.

### **Priority**
Set the priority: [High/Medium/Low]

## **Additional Details**
Add any other context about the task here.

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

### PR DESCRIPTION
**Pull request by XSTRANGER-7**
"I've crafted a fully responsive & UI Enhanced Login Page in which i used a lottie also which is visible on desktops and tabs & on phones , i have designed only login page and also used Zod library through which i have done input validation. If any user does not enter correct field or left blank, then it shows error."

This PR fixes #71 

Issue Title : [SignIn.jsx] - design an attractive signin page for curious connect #71 
Screenshots :

For Desktops- 
Screenshot (254)

Screenshot (252)

For Tabs -  
Screenshot (255)

Screenshot (256)

For Mobiles - 
Screenshot (257)

Video - 

https://github.com/Curious-Ecosystem/Curious-Connect/assets/92575432/a690d5db-be1b-4cc5-b074-8fd3761340e8

### CODE REVIEW

**Comment by UjjwalSaini07** [comment]
Great

**Comment by sarthak-stranger** [comment]
@UjjwalSaini07 Thank you

**Comment by sarthak-stranger** [comment]
@thecuriousteam Can you please check this?

**Comment by thecuriousteam** [comment]
image

There is some merge conflicts @sarthak-stranger

**Comment by thecuriousteam** [comment]
@sarthak-stranger route is not happening from signin button

**Pull request closed without merging**
