### PR TITLE
Add Hero-Section

### PR DESCRIPTION
**Pull request by niteshbca**
issue #17

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please share the screenshot

**Comment by niteshbca** [comment]
"C:\Users\LENOVO\Pictures\Screenshots\Screenshot 2024-05-12 131855.png"

**Comment by thecuriousteam** [comment]
Please check the figma design issue:#60

**Comment by niteshbca** [comment]
Please share the image hero section right google meeting ka

**Pull request closed without merging**
