### PR TITLE
Card Section Updated

### PR DESCRIPTION
**Pull request by siddhanttomar2003**
Final updates as discussed has been done plz merge it.

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach the screenshot @siddhanttomar2003 ?

**Comment by siddhanttomar2003** [comment]
Screenshot 2024-05-17 020933
Screenshot attached @thecuriousteam

**Comment by siddhanttomar2003** [comment]
@thecuriousteam  Can u plz merge it now

**Comment by siddhanttomar2003** [comment]
@thecuriousteam plz repond

**Comment by siddhanttomar2003** [comment]
@CDCNaman  Hlo, I think the card has been created as asked , but still there is pending pr ? Plz look after this

**Comment by siddhanttomar2003** [comment]
@thecuriousteam  plz respond

**Comment by thecuriousteam** [comment]
@siddhanttomar2003 we are in process of merging your code

**Comment by thecuriousteam** [comment]
We are merging your code @siddhanttomar2003

**Review by thecuriousteam — APPROVED** [review]

**Comment by siddhanttomar2003** [comment]
@thecuriousteam  THANKS FOR GIVING ME THIS OPPORTUNITY. ALWAYS UP TO CONTRIBUTE MORE

**Pull request merged**
