### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by SaranshBangar**
Resolves issue #169 

Description -> Added a favicon in the `index.html` file

Resolves image ->

image

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #227

**Comment by PratikMane0112** [comment]
I have already fixed it in #199

**Comment by thecuriousteam** [comment]
can you check our asset folder we have high resolution images, please can you add @SaranshBangar

**Comment by SaranshBangar** [comment]
> can you check our asset folder we have high resolution images, please can you add @SaranshBangar

Sir, I have used favicon image from assets folder itself, the image path is `src/assets/Landing-Page-Assets/CDC.jpg`

**Comment by SaranshBangar** [comment]
@thecuriousteam Is there any issue in my PR?

**Review by thecuriousteam — APPROVED** [review]

**Pull request merged**
