### PR TITLE
fixes: #255 navbar is responsive and attractive for mobile devices

### PR DESCRIPTION
**Pull request by anuragnegi000**
before:- 
before

after:- 
https://github.com/Curious-Ecosystem/Curious-Connect/assets/115611556/555b3998-aa89-4c8c-83d4-b82865fb72a3

### CODE REVIEW

**Comment by UjjwalSaini07** [comment]
Good Efforts.

**Comment by anuragnegi000** [comment]
thanks

**Comment by anuragnegi000** [comment]
This PR includes #212 and #255

**Comment by anuragnegi000** [comment]
@gnnandan

**Pull request closed without merging**
