### PR TITLE
Added team member page on landing page

### PR DESCRIPTION
**Pull request by raghavawasthi24**
Fixes : #20 
Screenshot (230)

### CODE REVIEW

**Comment by raghavawasthi24** [comment]
@thecuriousteam I have made changes as suggested and  closed previous PR

**Comment by thecuriousteam** [comment]
@raghavawasthi24 don't change the folder structure, we are using the tailwindcss please write the code according to it

**Comment by raghavawasthi24** [comment]
@thecuriousteam there is one component which is getting used in OurTeam page.
Where do I keep that as OurTeam is already in components folder?

**Comment by raghavawasthi24** [comment]
@thecuriousteam , I have modified folder structure . Please review.

**Comment by raghavawasthi24** [comment]
@thecuriousteam can you please merge this PR?

**Comment by thecuriousteam** [comment]
image

Please check the issue #60

**Pull request closed without merging**
