### PR TITLE
Update Contact.jsx

### PR DESCRIPTION
**Pull request by UjjwalSaini07**
Updated the contact Page with Container Enhancements & Framer Motion Animations.

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach the screenshot @UjjwalSaini07 ?

**Comment by UjjwalSaini07** [comment]
[

https://github.com/Curious-Ecosystem/Curious-Connect/assets/73696489/7954c142-b4a8-457b-b922-37497f33d87d

](url)

**Comment by nachatra-sharma** [comment]
image

Improve this little bit means you can see that while hovering the button it's going out of the container.

**Comment by UjjwalSaini07** [comment]
But brother this is hover effect means animation make website or program more attractive.

**Comment by nachatra-sharma** [comment]
yes you're right but as you can see while hovering button it going out of the container i am just saying that you have to make it less scaleable like on x-axis you can reduce the scale amount so that it not overflowing from the container.

**Comment by UjjwalSaini07** [comment]
okay brother I do that thing.
Thanx for suggesting and raise a minor issue in this, anything else u want to conclude in this which i want to correct them

**Comment by nachatra-sharma** [comment]
everything else is awesome bro @UjjwalSaini07

**Pull request closed without merging**
