### PR TITLE
Updated 404 error page

### PR DESCRIPTION
**Pull request by PratikMane0112**
Fix issue #170 Updating Error Page.

Before - 

After - 

Desktop View -

Screenshot 2024-05-19 195535

Mobile View -

Screenshot 2024-05-19 195523

### CODE REVIEW

**Comment by thecuriousteam** [comment]
this is not visible @PratikMane0112

**Comment by PratikMane0112** [comment]
OK, I will look into it.

**Comment by PratikMane0112** [comment]
Check now i have made changes - 
URLs : 
http://localhost:5173/ => HomePage
http://localhost:5173/aboutUs => AboutUsPage
http://localhost:5173/contactUs => ContactUsPage
http://localhost:5173/faq => FAQ page
 
 Any randomn url like below -
 
http://localhost:5173/sbjsb => ErrorPage

Screenshot 2024-05-20 165712

**Comment by PratikMane0112** [comment]
Enhancements

**Comment by thecuriousteam** [comment]
code is not running @PratikMane0112

**Comment by PratikMane0112** [comment]
Can you tell what exactly is not working.

**Pull request merged**
