### PR TITLE
[Footer.jxs] - Create a responsive footer #11 under GSSOC'24

### PR DESCRIPTION
**Pull request by dhyaneshsiddhartha15**
### Add a responsive footer with hover effects on icons

This commit adds a responsive footer to the website, enhancing user experience. Icons in the footer now move slightly up and change color to blue when hovered over, providing visual feedback and in Footer Content is added based on "Curious-Connect" Website Theme 
The changes also improve the footer's responsiveness across different screen sizes. A video demonstration of the changes is included and also added "Subscribes News Letter" form so that User get Daily News ,Updates in given emails" (only frontend part)
@thecuriousteam  could you please review these changes? Once approved, we can merge this pull request.

 Images showing 
gssoc
###   Video Showing
[5_12_2024, 1_02_12 AM - Screen - Untitled video.webm](https://github.com/Curious-Ecosystem/Curious-Connect/assets/157828240/dd81c1b5-2819-4ac5-ab28-7aac1775ce55)

### CODE REVIEW

**Comment by thecuriousteam** [comment]
We are testing @dhyaneshsiddhartha15

**Comment by thecuriousteam** [comment]
We are not able to see your code @dhyaneshsiddhartha15

**Comment by thecuriousteam** [comment]
Please reach-out to admins [Curious Connect Project Admins](https://wa.link/4b9c7o) with your issue number and don't forget to join [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)

**Comment by dhyaneshsiddhartha15** [comment]
@thecuriousteam  Sorry for the issues but You are not able to see my code fo my Branch?

**Comment by thecuriousteam** [comment]
Hello
Please take the latest pull from main or hit the sync-fork and again raise the pull request

**Comment by thecuriousteam** [comment]
Can we connect?
Please raise pull request to main only

**Comment by thecuriousteam** [comment]
Please reach-out to admins [Curious Connect Project Admins](https://wa.link/hrn0z8) with your issue number and don't forget to join [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)

Your Default Meeting Link - https://meet.google.com/bwp-aasw-xbk

**Pull request closed without merging**
