### PR TITLE
Added 'About', 'Contact' and 'FAQ' Pages

### PR DESCRIPTION
**Pull request by yashmandi**
- Added Added 'About', 'Contact' and 'FAQ' Pages in Footer
- Created Page Routing using React Router DOM and now user can easily jump from one page to another (only from footer section)
- Would like to work on entire Footer pages under GSSOC '24, if assigned ;)

https://github.com/Curious-Ecosystem/Curious-Connect/assets/132436131/e022ec07-dfea-4b42-a344-bef16159ffa0

### CODE REVIEW

**Review by thecuriousteam — COMMENTED** [review]
@yashmandi you are in GSSOC Group? Please ping us

**Comment by yashmandi** [comment]
> @yashmandi you are in GSSOC Group? Please ping us

yes, i have sent a request to join your whatsapp community

**Comment by thecuriousteam** [comment]
Please join the call @yashmandi

**Comment by yashmandi** [comment]
Hi @thecuriousteam , i have made the necessary changes in folder structure.

**Comment by thecuriousteam** [comment]
image

Move this inside the footer folder brother

**Comment by yashmandi** [comment]
updated 👍

Screenshot (198)

**Review by thecuriousteam — APPROVED** [review]

**Pull request merged**
