### PR TITLE
enhancing_about_us_from_with_adding_ourTem_section_with_some_animations

### PR DESCRIPTION
**Pull request by AnitSarkar123**
solve issue #141
vedio

https://github.com/Curious-Ecosystem/Curious-Connect/assets/135215478/f75e3901-f961-4ba3-b968-f671255eadcf

plese review it and meagre it

### CODE REVIEW

**Comment by thecuriousteam** [comment]
@AnitSarkar123 can you check there is some responsive issue

**Comment by thecuriousteam** [comment]
image

**Comment by AnitSarkar123** [comment]
Ok

**Comment by thecuriousteam** [comment]
Yes @AnitSarkar123

**Pull request closed without merging**
