### PR TITLE
Added and Corrected the Initial Files of the Zod 

### PR DESCRIPTION
**Pull request by ujjwalagrawal-1**
#133  Solved 
Please review the Files 

Corrected this **https://github.com/Curious-Ecosystem/Curious-Connect/pull/153** Pull Request 

Some of the SS  are -> 
Screenshot 2024-05-17 173048
Screenshot 2024-05-17 173016
Screenshot 2024-05-17 172743

and  also Corrected 
#152 

image

### CODE REVIEW

**Comment by CDCNaman** [comment]
@ujjwalagrawal-1 
Thanks for your Contribution, this is exactly what is required with a very small minor bug.
You have imposed the same Registration Schema Validation middleware on both sign up and sign in route 
That is why it is asking for username as well on sign-in as well
image

**Comment by CDCNaman** [comment]
@ujjwalagrawal-1 and sorry I am asking for changes 2nd time, but its required.
So Please let me know will you make changes otherwise we can raise one more issue for the remaining changes.

**Comment by thecuriousteam** [comment]
@ujjwalagrawal-1 brothe please can you make those changes?

**Comment by thecuriousteam** [comment]
We have given level3 can you update it brother?

**Comment by CDCNaman** [comment]
@ujjwalagrawal-1 Definitely I will check today and sorry for delay.

**Review by CDCNaman — APPROVED** [review]

**Comment by CDCNaman** [comment]
@ujjwalagrawal-1 I have approved your PR soon @thecuriousteam will merge this

**Pull request merged**
