### PR TITLE
Final Meeting Crds Added

### PR DESCRIPTION
**Pull request by manpreet244**
in previous pull request , I have made wrong merge , from base featuer.IntialUIDesign to main feature/InitialUIDesign 
sorry for the conflict , This is the final one ,.pls review
image

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Can you react-icons @manpreet244 ?

**Comment by manpreet244** [comment]
okay , i will change this ,,
what about responsivenes? is it okay or any change u want to?

**Comment by thecuriousteam** [comment]
It is not running as of now, we are checking

**Comment by thecuriousteam** [comment]
image

There are 2 meeting in 3rd card

**Comment by thecuriousteam** [comment]
Please add colors in the component instead of tailwindcss.config

**Review by thecuriousteam — CHANGES_REQUESTED** [review]
Please refer the comments

**Comment by manpreet244** [comment]
okay

**Pull request merged**
