### PR TITLE
Responsive Sign Up and Sign In Completed

### PR DESCRIPTION
**Pull request by amnipriyasowrirajan**
I have created a Desktop and mobile responsive signup and sign-in page. I have also completed the validation.
 signupSign Up
signin Sign In

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach a screenshot @amnipriyasowrirajan

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by Adhil523** [comment]
> I have created a Desktop and mobile responsive signup and sign-in page. I have also completed the validation.  signupSign Up signin Sign In

Design looks generic. Try aligning it with the project's design(logo,colours etc)

**Comment by thecuriousteam** [comment]
@Adhil523 the image is not visible

**Comment by amnipriyasowrirajan** [comment]
ok.I will do it @Adhil523

**Comment by thecuriousteam** [comment]
Any updates @amnipriyasowrirajan @Adhil523

**Comment by thecuriousteam** [comment]
image

**Pull request closed without merging**
