### PR TITLE
flickering fixed

### LINKED ISSUE #184: [JoinWithCode.jsx] -  Solve Flickering Issue In JoinWithCode.jsx for the landing page component.
## **Task Description**

In this issue we have to solve a issue flickering in JoinWithCode.jsx  i.e. whenever anyone hovers on join room button the input box shifts a little right. 

## **Requirements:-**

Should be responsive.

Should be same as Figma design.

## **Goals and objectives**

To achieve the required output.

## **Branch Name**
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

## **Deadline**
20/05/2024

## **Priority**
Medium

## Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

### PR DESCRIPTION
**Pull request by hars-21**
#184 fixed

Successfully fixed the flickering issue which created by hovering on join button.

https://github.com/Curious-Ecosystem/Curious-Connect/assets/144909381/828a1d47-0554-48e3-bfe8-ea6c574dad11

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please can you recheck about thie @hars-21

**Comment by hars-21** [comment]
Hey @thecuriousteam I have rechecked with latest pull and flickering is resolved now. Please review.

https://github.com/Curious-Ecosystem/Curious-Connect/assets/144909381/7f57d356-a0e2-4538-80b9-845d84c848fa

**Comment by hars-21** [comment]
@thecuriousteam  Please review my PR. I have tested with the latest pull.

**Comment by hars-21** [comment]
@thecuriousteam Please review this PR

**Pull request merged**
