### PR TITLE
Redesigning meeting cards for landing pages in the MeetingCard.jsx component. (Done for both mobile devices and laptop devices)

### PR DESCRIPTION
**Pull request by anuragnegi000**
Before :-
before

After :- 
after

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach screenshot @anuragnegi000

**Comment by anuragnegi000** [comment]
@thecuriousteam Screenshots uploaded sir, kindly check

**Comment by thecuriousteam** [comment]
Can you change some more, this is our old design @anuragnegi000

**Comment by anuragnegi000** [comment]
@thecuriousteam Sure what specific do you want, do you have any demo?

**Comment by thecuriousteam** [comment]
Definitely you can check some other sample and add your own style @anuragnegi000

**Comment by anuragnegi000** [comment]
@thecuriousteam okay cool, gimme some time

**Pull request closed without merging**
