### PR TITLE
feat:responsive navbar

### PR DESCRIPTION
**Pull request by Adhil523**
### Responsive Navbar for assignment of #127 

image_2024-05-17_011354358
Screenshot 2024-05-17 011149

### Description of Feature

Responsive Navbar has been developed for Curious Connect as a component  `<Navbar/>` . Previously, no such feature had existed in this project, making navigation extremely difficult. 

### Features incorporated

1. Highlighting of selected tabs
2. Navigation across defined routes
3. Responsive design
4. Hamburger menu for smaller devices

### External libraries used

1. React Icons - `npm install react-icons`

### CODE REVIEW

**Review by thecuriousteam — CHANGES_REQUESTED** [review]
image

**Comment by thecuriousteam** [comment]
Can you make full width

image

**Comment by thecuriousteam** [comment]
image

Can you make header full width

**Comment by Adhil523** [comment]
> image
> 
> Can you make header full width

done

**Comment by Adhil523** [comment]
> Can you make full width
> 
> image

done

**Comment by Adhil523** [comment]
> image

changes made. please mention any changes if required

**Comment by Adhil523** [comment]
@thecuriousteam 
Requested changes have been made in `Navbar` component. Please review them and add on any other changes if required

**Comment by Adhil523** [comment]
> > image
> > Can you make header full width
> 
> done

**Review by Adhil523 — COMMENTED** [review]
Changes viewed and commit has been made fixing those. Please review and add on any more comments if required.

**Comment by Adhil523** [comment]
> image

fixed design issue

**Comment by thecuriousteam** [comment]
@Adhil523 your image is not visible

**Review by Adhil523 — COMMENTED** [review]
image_2024-05-18_225152834
Screenshot 2024-05-18 225036
Issues resolved and new implementations have been committed

**Review by thecuriousteam — APPROVED** [review]

**Comment by thecuriousteam** [comment]
We are merging your code @Adhil523

**Pull request merged**
