### PR TITLE
[Footer.jsx] - Footer Component Completed !

### PR DESCRIPTION
**Pull request by sarthu210**
The Footer Component was Completed as per the provided Figma prototype (Colors and other things are same as per the prototype)

Video of Proof:

https://github.com/Curious-Ecosystem/Curious-Connect/assets/94531691/9c7606e7-215b-4002-8a8f-758daf07ebc1

### Checklist

- [x] My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  My changes generate no new warnings
- [x]  My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Hi

we are getting this error

image

**Comment by thecuriousteam** [comment]
We are not able to see your code
image

**Comment by sarthu210** [comment]
> We are not able to see your code image

Sorry but this is not my code you can recheck my pull request I just created components name folder in side of that two files are there Footer.jsx and index. jsx

**Comment by sarthu210** [comment]
> We are not able to see your code image

My Footer code is out of the src file of components file

**Comment by sarthu210** [comment]
When I created this pull request the structure of folders are different due to this problem is occurred.

**Comment by sarthu210** [comment]
I will fix this today it self but please Mannualy check it once for me

**Pull request closed without merging**
