### PR TITLE
Creating joinRoom and handling the Joinroom functionalities

### PR DESCRIPTION
**Pull request by tusharyadav11**
Creating and **Handlingchanges** of **room** **names** and handling errors of it .
Placeholder logic for joining or **creating a room**.
It Clear any existing error messages.
The **handleRoomNameChange** function updates the **roomName** state based on user input.
The component renders:
A heading and input field for entering a room name.
Buttons for joining or creating a room.
**An error message if necessary.**

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach some screenshot @tusharyadav11

**Comment by thecuriousteam** [comment]
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Comment by tusharyadav11** [comment]
@thecuriousteam

**Comment by thecuriousteam** [comment]
Please check the the figma design @tusharyadav11

**Comment by thecuriousteam** [comment]
image

**Comment by thecuriousteam** [comment]
any updates @tusharyadav11

**Comment by tusharyadav11** [comment]
yes 

> any updates @tusharyadav11



> any updates @tusharyadav11

yes providing you soon

**Comment by tusharyadav11** [comment]
@thecuriousteam  earlier I pushed into main branch then you asked me to in different branch irrespective of main branch

**Comment by thecuriousteam** [comment]
Please any updates @tusharyadav11

**Comment by tusharyadav11** [comment]
Providing you soon

**Comment by thecuriousteam** [comment]
any updates?

**Pull request closed without merging**
