### PR TITLE
FooterAdded/Issue 11

### PR DESCRIPTION
**Pull request by dhyaneshsiddhartha15**
### Add a responsive footer with hover effects on icons
**Icons Used** - React Icons

>  Installation

 -  _npm i react-icons_
 - 
This commit adds a responsive footer to the website, enhancing user experience.
- Icons in the footer now move slightly up and change color to blue when hovered over, providing visual feedback and in --Footer Content is added based on "Curious-Connect" Website Theme

-The changes also improve the footer's responsiveness across different screen sizes. Added "Subscribe News Letter" form so that User get Daily News ,Updates in given emails" (only frontend part)
@thecuriousteam could you please review these changes? Once approved, we can merge this pull request.
A video demonstration of the changes is included 
### Image
curios

### 
Video

https://github.com/Curious-Ecosystem/Curious-Connect/assets/157828240/f306b297-0d7a-4402-8548-11874a5ae7e9

### CODE REVIEW

**Review by thecuriousteam — CHANGES_REQUESTED** [review]
image

Please can you change design according and check if its responsive or not

**Comment by dhyaneshsiddhartha15** [comment]
@thecuriousteam  Sure I will make changes according to your design and make sure its responsive!

**Comment by thecuriousteam** [comment]
Any updates @dhyaneshsiddhartha15 ?

**Comment by dhyaneshsiddhartha15** [comment]
Contenfoooter
 @thecuriousteam  Do See the Image and make me sure that it is fulfilling your Design Needs! of Footer

**Pull request closed without merging**
