### PR TITLE
Card Updated

### LINKED ISSUE #123: [UI Enhancements] - Enhance the Features Card for curious connect (OWN Design Acceptable)
image

### PR DESCRIPTION
**Pull request by siddhanttomar2003**
Card has been updated 
Fix #123 
Updations has been shared in Fix #123

### CODE REVIEW

**Comment by thecuriousteam** [comment]
image

@siddhanttomar2003 can you give little more space between

**Comment by thecuriousteam** [comment]
you can also remove the read more

**Comment by thecuriousteam** [comment]
Yes @siddhanttomar2003

**Comment by manpreet244** [comment]
Yeah ,it's looking fine

**Comment by siddhanttomar2003** [comment]
@thecuriousteam  plz merge the pr

**Pull request closed without merging**
